import { Amplify } from 'aws-amplify';

// Runtime configuration injected via /aws-exports.js during deployment
declare global {
  interface Window {
    TALKNAVI_CONFIG?: {
      NEXT_PUBLIC_GRAPHQL_ENDPOINT: string;
      NEXT_PUBLIC_REGION: string;
      NEXT_PUBLIC_GRAPHQL_API_KEY: string;
    };
  }
}

const config = typeof window !== 'undefined' ? window.TALKNAVI_CONFIG : undefined;

console.log('Configuring Amplify with:', {
  endpoint: config?.NEXT_PUBLIC_GRAPHQL_ENDPOINT || process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT,
  region: config?.NEXT_PUBLIC_REGION || process.env.NEXT_PUBLIC_REGION,
});

// This would typically come from aws-exports.js generated by Amplify CLI or CDK outputs
Amplify.configure({
  API: {
    GraphQL: {
      endpoint: config?.NEXT_PUBLIC_GRAPHQL_ENDPOINT || process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || 'https://dummy.appsync-api.region.amazonaws.com/graphql',
      region: config?.NEXT_PUBLIC_REGION || process.env.NEXT_PUBLIC_REGION || 'us-east-1',
      defaultAuthMode: 'apiKey',
      apiKey: config?.NEXT_PUBLIC_GRAPHQL_API_KEY || process.env.NEXT_PUBLIC_GRAPHQL_API_KEY || 'da2-dummy'
    }
  }
});
