import { Amplify } from 'aws-amplify';

console.log('Configuring Amplify with:', {
  endpoint: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT,
  region: process.env.NEXT_PUBLIC_REGION,
});

// This would typically come from aws-exports.js generated by Amplify CLI or CDK outputs
Amplify.configure({
  API: {
    GraphQL: {
      endpoint: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || 'https://dummy.appsync-api.region.amazonaws.com/graphql',
      region: process.env.NEXT_PUBLIC_REGION || 'us-east-1',
      defaultAuthMode: 'apiKey',
      apiKey: process.env.NEXT_PUBLIC_GRAPHQL_API_KEY || 'da2-dummy'
    }
  }
});
